
package clientesoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

import modelo.Autores;
import modelo.Favoritos;
import modelo.InformacionAutor;
import modelo.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DbplWebServiceSOAP", targetNamespace = "http://soap/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DbplWebServiceSOAP {


    /**
     * 
     * @param arg0
     * @return
     *     returns stub.Autores
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap/DbplWebServiceSOAP/findAutoresRequest", output = "http://soap/DbplWebServiceSOAP/findAutoresResponse")
    public Autores findAutores(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns stub.InformacionAutor
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap/DbplWebServiceSOAP/findInformacionRequest", output = "http://soap/DbplWebServiceSOAP/findInformacionResponse")
    public InformacionAutor findInformacion(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap/DbplWebServiceSOAP/crearFavoritosRequest", output = "http://soap/DbplWebServiceSOAP/crearFavoritosResponse")
    public String crearFavoritos();

    /**
     * 
     * @param arg0
     * @return
     *     returns stub.Favoritos
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap/DbplWebServiceSOAP/findFavoritosRequest", output = "http://soap/DbplWebServiceSOAP/findFavoritosResponse")
    public Favoritos findFavoritos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap/DbplWebServiceSOAP/deleteAutorFavoritosRequest", output = "http://soap/DbplWebServiceSOAP/deleteAutorFavoritosResponse")
    public boolean deleteAutorFavoritos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns stub.Favoritos
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap/DbplWebServiceSOAP/addAutorFavoritosRequest", output = "http://soap/DbplWebServiceSOAP/addAutorFavoritosResponse")
    public Favoritos addAutorFavoritos(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://soap/DbplWebServiceSOAP/deleteBBDDRequest", output = "http://soap/DbplWebServiceSOAP/deleteBBDDResponse")
    public boolean deleteBBDD();

}
