
package clientesoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DbplWebServiceSOAPImplService", targetNamespace = "http://clientesoap/", wsdlLocation = "http://localhost:9999/ws/dblpservice?wsdl")
public class DbplWebServiceSOAPImplService
    extends Service
{

    private final static URL DBPLWEBSERVICESOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DBPLWEBSERVICESOAPIMPLSERVICE_EXCEPTION;
    private final static QName DBPLWEBSERVICESOAPIMPLSERVICE_QNAME = new QName("http://clientesoap/", "DbplWebServiceSOAPImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/dblpservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DBPLWEBSERVICESOAPIMPLSERVICE_WSDL_LOCATION = url;
        DBPLWEBSERVICESOAPIMPLSERVICE_EXCEPTION = e;
    }

    public DbplWebServiceSOAPImplService() {
        super(__getWsdlLocation(), DBPLWEBSERVICESOAPIMPLSERVICE_QNAME);
    }

    public DbplWebServiceSOAPImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DBPLWEBSERVICESOAPIMPLSERVICE_QNAME, features);
    }

    public DbplWebServiceSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, DBPLWEBSERVICESOAPIMPLSERVICE_QNAME);
    }

    public DbplWebServiceSOAPImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DBPLWEBSERVICESOAPIMPLSERVICE_QNAME, features);
    }

    public DbplWebServiceSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DbplWebServiceSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DbplWebServiceSOAP
     */
    @WebEndpoint(name = "DbplWebServiceSOAPImplPort")
    public DbplWebServiceSOAP getDbplWebServiceSOAPImplPort() {
        return super.getPort(new QName("http://clientesoap/", "DbplWebServiceSOAPImplPort"), DbplWebServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DbplWebServiceSOAP
     */
    @WebEndpoint(name = "DbplWebServiceSOAPImplPort")
    public DbplWebServiceSOAP getDbplWebServiceSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://clientesoap/", "DbplWebServiceSOAPImplPort"), DbplWebServiceSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DBPLWEBSERVICESOAPIMPLSERVICE_EXCEPTION!= null) {
            throw DBPLWEBSERVICESOAPIMPLSERVICE_EXCEPTION;
        }
        return DBPLWEBSERVICESOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
